name: PROXY Updater

on:
  # Roda a cada 3 horas
  schedule:
    - cron: '0 */3 * * *'
    
  # # Roda automaticamente ao atualizar a branch updater
  # push:
  #   branches:
  #     - updater  
  
  # Roda manualmente
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  update-proxy:
    runs-on: ubuntu-latest
    steps:
      # Checkout da branch updater
      - name: Checkout updater branch
        uses: actions/checkout@v3
        with:
          ref: updater
          token: ${{ secrets.REPO_TOKEN }}

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run updater script
        run: python update_proxy.py

      # Agora troca para a branch main
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.REPO_TOKEN }}

      # Copia o arquivo gerado da workspace anterior
      - name: Copy proxy file
        run: cp ../proxyssl/proxy_http_ssl.txt proxy_http_ssl.txt || true

      - name: Commit and push
        run: |
          git config user.name "${{ secrets.GIT_NAME }}"
          git config user.email "${{ secrets.GIT_EMAIL }}"
          git add proxy_http_ssl.txt
          git commit -m "Update proxy_http_ssl.txt" || echo "No changes"
          git push origin main
