name: PROXY Updater

on:
  # Roda a cada 3 horas
  schedule:
    - cron: '0 */3 * * *'
    
  # # Roda automaticamente ao atualizar a branch updater
  # push:
  #   branches:
  #     - updater  
  
  # Roda manualmente
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  update-proxy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar o repositório na branch updater
      - name: Checkout updater branch
        uses: actions/checkout@v3
        with:
          repository: zoreu/proxyssl
          ref: updater
          token: ${{ secrets.REPO_TOKEN }}

      # 2. Configurar Python 3.11
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Instalar dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # 4. Rodar o script update_proxy.py
      - name: Run updater script
        run: python update_proxy.py

      # 5. Configurar Git
      - name: Configure Git
        run: |
          git config --local user.email "${{ secrets.GIT_EMAIL }}"
          git config --local user.name "${{ secrets.GIT_NAME }}"
      # 6. Copiar arquivo atualizado para a branch main
      - name: Push proxy file to main branch
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.REPO_TOKEN }}@github.com/zoreu/proxyssl.git
          git add proxy_http_ssl.txt
          git commit -m "Update proxy_http_ssl.txt from updater branch" || echo "No changes to commit"
          git push origin updater:main --force
